reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"



  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :create, :new, :destroy]
  resources :subs, only: [:index, :show, :new, :create, :destroy]
  resources :posts, only: [:index, :show, :create, :destroy]
  get 'posts/:sub_id/new', to: 'posts#new'

end

reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

reddit_clone/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  body       :string
#  url        :string           not null
#  poster_id  :bigint
#  sub_id     :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
    validates :title, presence: true

    belongs_to :poster,
        foreign_key: :poster_id,
        class_name: :User,
        inverse_of: :posts
    
    belongs_to :sub,
        foreign_key: :sub_id,
        class_name: :Sub,
        inverse_of: :posts


end

reddit_clone/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :bigint           not null, primary key
#  title        :string           not null
#  moderator_id :bigint
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Sub < ApplicationRecord
    validates :title, presence: true, uniqueness: true

    has_many :posts,
        foreign_key: :sub_id,
        class_name: :Post,
        inverse_of: :sub
    
    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User,
        inverse_of: :subs
end

reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    validates :username, :session_token, presence: true, uniqueness: true
    validates :password_digest, presence: true

    before_validation :ensure_session_token

    attr_reader :password

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        
        if user != nil
            return user.is_password?(password) ? user : nil
        else
            return nil
        end
    end

    def ensure_session_token
        self.session_token ||= generate_unique_random_session_token
    end

    def generate_unique_random_session_token
        token = SecureRandom.urlsafe_base64
        token = SecureRandom.urlsafe_base64 while User.find_by(session_token: token) != nil
        return token
    end

    def reset_session_token!
        self.session_token = generate_unique_random_session_token
        self.save!
        return self.session_token
    end

    def password=(password)
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        password_obj = BCrypt::Password.new(self.password_digest)
        return password_obj.is_password?(password)
    end


    has_many :subs,
        foreign_key: :moderator_id,
        class_name: :Sub,
        inverse_of: :moderator
    
    has_many :posts,
        foreign_key: :poster_id,
        class_name: :Post,
        inverse_of: :poster

end

reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def login(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def logout
        @current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

end

reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
        render :index
    end

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end

    def new
        @post = Post.new
        @sub_id = params[:sub_id]
        render :new
    end

    def create

        @post = Post.new(title: post_params[:title], body: post_params[:body], poster: current_user, sub: Sub.find_by(id: post_params[:sub_id]))

        debugger
        if @post.save!
            redirect_to post_url(@post.id)
        else
            flash.new[:errors] = ["Failed to Create Post"]
        end
    end

    def post_params
        params.require(:post).permit(:title, :body, :sub_id)
    end

end

reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new
        render :new
    end


    def create
        @user = User.find_by_credentials(user_params[:username], user_params[:password])

        if @user != nil
            login(@user)
            redirect_to users_url
        else
            flash.now[:errors] = ["Invalid Credentials"]
            redirect_to new_session_url
        end
    end

    def destroy
        logout
        flash[:messages] = ["Successfully logged out"]
        redirect_to new_session_url
    end

    def user_params
        params.require(:user).permit(:username, :password)
    end

end

reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    def index
        @subs = Sub.all
        render :index
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(title: sub_params[:title], moderator: current_user)

        if @sub.save!
            redirect_to sub_url(@sub.id)
        else
            flash.new[:errors] = "Failed to create sub"
        end
    end
end

reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(username: params[:user][:username], password: params[:user][:password])

        if @user.save!
            redirect_to users_url
        else
            flash.now[:errors] = "Failed to create User"
        end
    end
end

reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_clone/app/helpers/session_helper.rb
module SessionHelper
end

reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit_clone/app/views/layouts/_header.html.erb
<nav>
<div class='nav-links'>
<a href="<%=users_url%>">All Users</a>
<a href="<%=posts_url%>">All Posts</a>
<a href="<%=subs_url%>">All Subs</a>
</div>

<% if current_user != nil %>
    <div class='signed-in-links'>
    <span>Logged in as <%= current_user.username %></span>
    <form action="<%= session_url %>" method="DELETE">
    <input type="hidden" name="method" value="DELETE">
    <input type="hidden" name="authenticity-token" value="<%= @form_authenticity_token%>">
    <input type="Submit" value="Log Out">
    </form>
    </div>
<% else %>
    <div class='sign-in-links'>
    <a href="<%=new_session_url%>">Log In</a></div>
    <a href="<%=new_user_url%>">Create User</a></div>
    </div>
<% end %>
</nav>

reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

reddit_clone/app/views/posts/index.html.erb
<%= render 'layouts/header' %>
<h1>All Posts</h1>

<% @posts.each do |post| %>
    <div class='block'>
    <a href="<%=post_url(post.id)%>"><h2><%=post.title%></h2></a>
    <h3>Posted by: <a href="<%=user_url(post.poster.id)%>"><%=post.poster.username%></a> in <a href="<%=sub_url(post.sub.id)%>"><%=post.sub.title%></a></h3>
    <p><%=post.body%></p>
    </div>
<% end %>

reddit_clone/app/views/posts/new.html.erb
<%= render 'layouts/header' %>
<h1>Create Post</h1>
<form action="<%=posts_url%>" method="POST">
<input type="hidden" name="authenticity-token" id="" value="<%=form_authenticity_token%>">
<input type="hidden" name="post[sub_id]" id="" value="<%=params[:sub_id]%>">
<label for="title-input">
<input type="text" name="post[title]" id="title-input" value="<%=@post.title%>">
</label>
<label for="body-input">
<input type="text" name="post[body]" id="body-input" value="<%=@post.body%>">
</label>
<input type="submit" name="" id="" value="Post">
</form>

reddit_clone/app/views/posts/show.html.erb
<%= render 'layouts/header' %>
<h1><%=@post.title%></h1>
<p><%=@post.body%></p>
<h4>Posted by <a href="<%=user_url(@post.poster.id)%>"><%=@post.poster.username%></a> in <a href="<%=sub_url(@post.sub.id)%>"><%=@post.sub.title%></a></h4>
<h3>Comments:</h3>

reddit_clone/app/views/subs/index.html.erb
<%= render 'layouts/header' %>
<h1>All Subs</h1>

<% @subs.each do |sub| %>
    <div class='block'>
    <a href='<%= sub_url(sub.id) %>'><h2><%=sub.title%></h2></a>
    <h3>Moderated by <a href="<%=user_url(sub.moderator.id)%>"><%=sub.moderator.username%></h3></a>
    </div>
<% end %>

reddit_clone/app/views/subs/show.html.erb
<%= render 'layouts/header' %>
<h1><%=@sub.title%></h1>

<a href="/posts/<%=@sub.id%>/new">Create Post</a>


<% @sub.posts.each do |post| %>
    <div class='block'>
    <h3><a href="<%=post_url(post.id)%>"><%=post.title%></a> posted by <a href="<%= user_url(post.poster.id)%>"><%=post.poster.username%></h3>
    </div>
<% end %>

reddit_clone/app/views/users/index.html.erb
<%= render 'layouts/header' %>


<h1>All Users</h1>


<% @users.each do |user| %>
    <div class="block">
        <a href="<%=users_url%>/<%=user.id%>"><span class='username'><%=user.username%></span></a>
    </div>
<% end%>

reddit_clone/app/views/users/new.html.erb
<%= render 'layouts/header' %>
<h1>Create a New User</h1>
<form action="<%=users_url%>" method="POST">
<input type="hidden" name="validity-token" id="" value="<%=@form_validity_token%>">
<label for="username-input">
<input type="text" name="user[username]" id="username-input" placeholder="Username" value="<%=@user.username%>">
</label>
<label for="password-input">
<input type="password" name="user[password]" id="password-input" placeholder="password" value="">
</label>
<input type="submit" name="" id="" value="Create User">
</form>

reddit_clone/app/views/users/show.html.erb
<%= render 'layouts/header' %>
<h1><%=@user.username%>'s Page</h1>
<h2>Moderated Subs:</h2>
<% @user.subs.each do |sub| %>
    <div class='block'>
    <a href="<%=sub_url(sub.id)%>"><h3><%=sub.title%></h3></a>
    </div>
<% end %>
<h2>Posts:</h2>

<% @user.posts.each do |post| %>
    <div class='block'>
    <a href="<%=post_url(post.id)%>"><h3><%=post.title%></h3></a>
    </div>
<% end %>